---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

environments:
    development:
        bootstrap:
            insert:
                properties : false
                provinces : true
        grails:
            mongodb:
                host: "localhost"
                port: 27017
                databaseName: "vivareal"      
    test:        
        grails:   
            mongodb:
                host: "localhost"
                port: 27017
                databaseName: "vivarealtest"
    production:
        bootstrap:
            insert:
                properties : false
                provinces : true
        grails:           
            mongodb:
                host: "localhost"
                port: 27017
                databaseName: "vivareal"

---
---
grails:
    profile: rest-api
    codegen:
        defaultPackage: vivareal
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: 'v1'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false
# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8 
---
---
 spotippos:
    limit:
        x: 1400
        y: 1000
